import { useEffect, useState } from 'react';
import { FolderKanban, Trash2, UserRound } from 'lucide-react';
import { emptyDetails, id, load, save } from './store';
import type { Data, DriverProfile, Project, Sponsor, TemplateId } from './types';
import { Builder } from './components/builder/Builder';
import { Upload } from './components/forms/ImageUpload';
import { Sidebar } from './components/navigation/Sidebar';
import { PageHeader } from './components/ui';
import { MOTORSPORT_FONTS } from './config/branding';
import type { PageId } from './config/navigation';
import { TEMPLATE_CATALOGUE } from './config/templates';
import { HomePage, TemplateLibraryPage } from './pages';
import { getImageDimensions } from './utils/images';
export default function App(){
 const [data,setData]=useState<Data>(load); const [page,setPage]=useState<PageId>('home'); const [activeId,setActiveId]=useState<string>();
 useEffect(()=>save(data),[data]);
 if(!data.onboardingComplete)return <Onboarding data={data} finish={d=>{setData({...d,onboardingComplete:true});setPage('templates')}}/>;
 const active=data.projects.find(p=>p.id===activeId);
 const openTemplate=(template:TemplateId)=>{const p:Project={id:id('graphic'),name:TEMPLATE_CATALOGUE.find(t=>t.id===template)?.name||'Graphic',template,format:'feed',sponsorIds:data.sponsors.slice(0,10).map(s=>s.id),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),heroImage:'',heroImageWidth:0,heroImageHeight:0,heroX:0,heroY:0,heroScale:1,heroFlip:false,driverX:0,driverY:0,driverScale:1,driverVisible:true,details:{...emptyDetails}};setData(d=>({...d,projects:[p,...d.projects]}));setActiveId(p.id);setPage('builder')};
 const patchProject=(patch:Partial<Project>)=>setData(d=>({...d,projects:d.projects.map(p=>p.id===activeId?{...p,...patch,updatedAt:new Date().toISOString()}:p)}));
 const appStyle:any={'--brand-primary':data.branding.primary,'--brand-secondary':data.branding.secondary,'--brand-accent':data.branding.accent,'--brand-heading':data.branding.headingFont,'--brand-body':data.branding.bodyFont};
 return <div className="app" style={appStyle}><Sidebar activePage={page} onNavigate={setPage}/><main>
  {page==='home'&&<HomePage data={data} openTemplate={openTemplate} openTemplates={()=>setPage('templates')}/>} 
  {page==='templates'&&<TemplateLibraryPage openTemplate={openTemplate}/>} 
  {page==='profile'&&<ProfilePage data={data} setData={setData}/>} 
  {page==='branding'&&<BrandingPage data={data} setData={setData}/>} 
  {page==='sponsors'&&<SponsorsPage data={data} setData={setData}/>} 
  {page==='saved'&&<SavedPage data={data} setData={setData} open={p=>{setActiveId(p.id);setPage('builder')}}/>}
  {page==='builder'&&active&&<Builder data={data} project={active} patch={patchProject} back={()=>setPage('templates')}/>} 
 </main></div>
}

function Onboarding({data,finish}:{data:Data;finish:(d:Data)=>void}){const [draft,setDraft]=useState(data);const p=draft.profile;const valid=p.name.trim()&&p.number.trim();return <div className="onboarding"><div className="onboarding-card"><div className="logo large"><span>MF</span><div><b>MEDIA FACTORY</b><small>DRIVER GRAPHICS</small></div></div><span className="eyebrow">WELCOME</span><h1>Create your driver profile</h1><p>Your profile supplies the permanent details and assets used across your templates. Hero images are selected separately for each graphic.</p><div className="onboarding-grid"><div className="portrait-upload">{p.driverImage?<img src={p.driverImage}/>:<UserRound size={54}/>}<Upload label="Driver image" purpose="portrait" on={v=>setDraft({...draft,profile:{...p,driverImage:v}})}/></div><div className="form-grid single">{(['name','number','team','car','location','age'] as const).map(k=><label key={k}>{labelFor(k)}<input value={p[k]} onChange={e=>setDraft({...draft,profile:{...p,[k]:e.target.value}})}/></label>)}<Upload label="Team logo" purpose="logo" on={v=>setDraft({...draft,profile:{...p,teamLogo:v}})}/><Upload label="Competition logo" purpose="logo" on={v=>setDraft({...draft,profile:{...p,competitionLogo:v}})}/></div></div><button className="primary wide" disabled={!valid} onClick={()=>finish(draft)}>Create profile</button></div></div>}

function ProfilePage({data,setData}:{data:Data;setData:(d:Data)=>void}){const p=data.profile;const update=(x:Partial<DriverProfile>)=>setData({...data,profile:{...p,...x}});return <div className="page"><PageHeader title="Driver profile" subtitle="Your permanent driver details, portrait and logos are reused across relevant templates."/><div className="profile-layout stacked"><div className="panel profile-inputs"><div className="form-grid">{(['name','number','team','car','location','age'] as const).map(k=><label key={k}>{labelFor(k)}<input value={p[k]} onChange={e=>update({[k]:e.target.value})}/></label>)}</div></div><div className="profile-previews"><AssetUploadPreview title="Driver image" image={p.driverImage} fallback={<UserRound size={48}/>} on={driverImage=>update({driverImage})}/><div className="logo-preview-stack"><AssetUploadPreview title="Team logo" image={p.teamLogo} fallback={<span>TEAM</span>} on={teamLogo=>update({teamLogo})}/><AssetUploadPreview title="Competition logo" image={p.competitionLogo} fallback={<span>COMP</span>} on={competitionLogo=>update({competitionLogo})}/></div></div></div></div>}
function AssetUploadPreview({title,image,fallback,on}:{title:string;image?:string;fallback:any;on:(v:string)=>void}){return <div className={`asset-preview-card ${title==='Driver image'?'driver-asset-preview':''}`}><div className="asset-preview-image">{image?<img src={image}/>:fallback}</div><Upload label={title} purpose={title.toLowerCase().includes('logo')?'logo':'portrait'} on={on}/></div>}
function BrandingPage({data,setData}:{data:Data;setData:(d:Data)=>void}){const b=data.branding,p=data.profile;const update=(x:any)=>setData({...data,branding:{...b,...x}});return <div className="page"><PageHeader title="Branding" subtitle="Set your preferred colours and fonts and review them in a contained template preview."/><div className="branding-layout"><div className="panel"><div className="form-grid"><label>Primary colour<input type="color" value={b.primary} onChange={e=>update({primary:e.target.value})}/></label><label>Secondary colour<input type="color" value={b.secondary} onChange={e=>update({secondary:e.target.value})}/></label><label>Accent colour<input type="color" value={b.accent} onChange={e=>update({accent:e.target.value})}/></label><label>Heading font<select value={b.headingFont} onChange={e=>update({headingFont:e.target.value})}>{MOTORSPORT_FONTS.map(f=><option key={f}>{f}</option>)}</select></label><label>Body font<select value={b.bodyFont} onChange={e=>update({bodyFont:e.target.value})}>{MOTORSPORT_FONTS.map(f=><option key={f}>{f}</option>)}</select></label></div></div><div className="branding-preview-shell"><div className="branding-preview-window" style={{background:`linear-gradient(145deg,${b.secondary},#050607)`}}><div className="preview-stripe" style={{background:b.primary}}/><div className="preview-copy" style={{color:b.accent}}><small style={{fontFamily:b.bodyFont}}>#{p.number||'00'} · {p.team||'YOUR TEAM'}</small><strong style={{fontFamily:b.headingFont}}>RACE WEEKEND</strong><span style={{fontFamily:b.bodyFont}}>BRAND PREVIEW</span></div><div className="preview-logos">{p.competitionLogo?<img src={p.competitionLogo}/>:<div>COMP</div>}{p.teamLogo?<img src={p.teamLogo}/>:<div>TEAM</div>}</div><div className="preview-sponsor-bar">SPONSOR BAR · 5 PER ROW</div></div></div></div></div>}
function SponsorsPage({data,setData}:{data:Data;setData:(d:Data)=>void}){const add=()=>{if(data.sponsors.length>=10)return;setData({...data,sponsors:[...data.sponsors,{id:id('sponsor'),name:'New Sponsor'}]})};const logoScale=data.branding.sponsorLogoScale||1;return <div className="page"><PageHeader title="Sponsors" subtitle={`${data.sponsors.length}/10 logos available for the locked sponsor bar.`}/><div className="sponsor-toolbar"><button className="primary inline-action" onClick={add} disabled={data.sponsors.length>=10}>Add sponsor</button><label className="sponsor-size-control">Logo visual size <span>{Math.round(logoScale*100)}%</span><input type="range" min="0.65" max="1.4" step="0.05" value={logoScale} onChange={e=>setData({...data,branding:{...data.branding,sponsorLogoScale:+e.target.value}})}/></label></div><p className="field-help">Transparent padding is removed automatically when a logo is uploaded. Logo dimensions are measured after transparent padding is removed, then each logo is normalised by visible area while preserving its proportions.</p><div className="stack">{data.sponsors.map(s=><SponsorCard key={s.id} s={s} update={p=>setData({...data,sponsors:data.sponsors.map(x=>x.id===s.id?{...x,...p}:x)})} remove={()=>setData({...data,sponsors:data.sponsors.filter(x=>x.id!==s.id)})}/>)}</div></div>}
function SponsorCard({s,update,remove}:{s:Sponsor;update:(p:Partial<Sponsor>)=>void;remove:()=>void}){const saveLogo=async(logo:string)=>{try{const size=await getImageDimensions(logo);update({logo,logoWidth:size.width,logoHeight:size.height})}catch{update({logo,logoWidth:undefined,logoHeight:undefined})}};return <div className="edit-card"><div className="brand-mark">{s.logo?<img src={s.logo}/>:s.name.slice(0,2)}</div><div className="form-grid"><label>Name<input value={s.name} onChange={e=>update({name:e.target.value})}/></label><Upload label="Logo" purpose="logo" on={saveLogo}/></div><button className="icon danger" onClick={remove}><Trash2 size={17}/></button></div>}
function SavedPage({data,setData,open}:{data:Data;setData:(d:Data)=>void;open:(p:Project)=>void}){const savedProjects=data.projects.filter(p=>p.exportedAt);return <div className="page"><PageHeader title="Saved graphics" subtitle="Reopen graphics that have been saved by exporting a PNG."/>{savedProjects.length===0?<div className="empty"><FolderKanban size={42}/><h3>No saved graphics yet</h3><p>A graphic is saved here when its PNG is exported.</p></div>:<div className="project-grid">{savedProjects.map(p=><div className="project-card" key={p.id}><div className={`project-thumb ${p.template}`}><span>{TEMPLATE_CATALOGUE.find(t=>t.id===p.template)?.name}</span></div><input value={p.name} onChange={e=>setData({...data,projects:data.projects.map(x=>x.id===p.id?{...x,name:e.target.value,updatedAt:new Date().toISOString()}:x)})}/><small>Saved {new Date(p.exportedAt!).toLocaleDateString()} · Updated {new Date(p.updatedAt).toLocaleDateString()}</small><div><button onClick={()=>open(p)}>Open</button><button className="icon danger" onClick={()=>setData({...data,projects:data.projects.filter(x=>x.id!==p.id)})}><Trash2 size={16}/></button></div></div>)}</div>}</div>}

const labelFor=(k:string)=>({name:'Driver name',number:'Car number',team:'Team name',car:'Car make/model',location:'Location',age:'Age'} as any)[k]||k;
